name: 'Kyma CLI'
description: 'A Github Action wrapping github.com/kyma-project/cli'
inputs:
  command:
    description: 'command to pass to the CLI'
    required: false
    default: 'help'
  version:
    description: 'the stability or version of the CLI, either stable or unstable or a release tag'
    required: true
    default: 'stable'
outputs:
  stdout:
    description: "The STDOUT of the Command"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  
    - uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/kyma-${{ inputs.version }}
        key: ${{ runner.os }}-kyma-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-kyma-${{ inputs.version }}
          
    - name: Download the CLI for ${{ runner.os }} ( ${{ input.version }} )
      id: download-storage-with-stability
      shell: bash
      if: ( inputs.version == 'stable' ) || ( input.version == 'unstable' )
      run: |
        EXEC=kyma-${{ inputs.version }}
        if [ ! -f "$EXEC" ]; then
          echo "$EXEC was never downloaded, looking up."
          wget -q https://storage.googleapis.com/kyma-cli-${{ inputs.version }}/kyma-linux
          chmod +x kyma-linux && mv kyma-linux $EXEC
        fi
    - name: Download the CLI for ${{ runner.os }} ( ${{ input.version }} )
      id: download-storage-with-version
      shell: bash
      if: ( inputs.version != 'stable' ) && ( input.version != 'unstable' )
      run: |
        EXEC=kyma-${{ inputs.version }}
        if [ ! -f "$EXEC" ]; then
          echo "$EXEC was never downloaded, looking up."
          wget -q https://github.com/kyma-project/cli/releases/download/${{ input.version }}/kyma_Linux_x86_64.tar.gz
          chmod +x kyma-linux && mv kyma-linux $EXEC
        fi
    
    - shell: bash
      run: |
        EXEC=/usr/local/bin/kyma-${{ inputs.version }}
        if [ ! -f "$EXEC" ]; then
            echo "$EXEC does not exist in path yet, adding."
            mv kyma-${{ inputs.version }} $EXEC
        fi
        
    - shell: bash
      run: alias kyma=kyma-${{ inputs.version }}
        
    - if: ${{ inputs.command != '' }}
      shell: bash
      run: kyma ${{ inputs.command }}
